version: "3.4"
services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build: .
    # environment:
    #   - APP_ENV=prod
    #   - APP_DEBUG=0
    volumes:
      - ./:/var/www/html
